plan/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from dream.views import (
    DreamListView, DreamCreateView, DreamEditView,
    PlanListView, PlanCreateView, PlanEditView,
    TaskToDoListView, TaskPurchasesListView, TaskCreateView, TaskEditView,
    IdeaListView, IdeaCreateView, IdeaEditView
)

admin.autodiscover()

dream_patterns = patterns('',
    # noqa
    url(r'^$', DreamListView.as_view(), name='list'),
    # url(r'^dreams/(?P<dream_filter>active|possible|reserve|staffed|finished|managed)/$',
    #     DreamListView.as_view(),
    #     name='list'),
    url(r'^dreams/new/$',
        DreamCreateView.as_view(),
        name='new'),
    url(r'^dreams/(?P<slug>[-_\w]+)/$',
        DreamEditView.as_view(),
        name='edit'),
)

plan_patterns = patterns('',
    # noqa
    url(r'^dreams/(?P<dream_slug>[-_\w]+)/plans/$',
        PlanListView.as_view(),
        name='list'),
    url(r'^dreams/(?P<dream_slug>[-_\w]+)/plans/new/$',
        PlanCreateView.as_view(),
        name='new'),
    url(r'^dreams/(?P<dream_slug>[-_\w]+)/plans/(?P<slug>[-_\w]+)/$',
        PlanEditView.as_view(),
        name='edit'),
)

task_patterns = patterns('',
    # noqa
    url(r'^tasks/to-do$',
        TaskToDoListView.as_view(),
        name='to_do_list'),
    url(r'^tasks/purchases$',
        TaskPurchasesListView.as_view(),
        name='purchase_list'),
    url(r'^tasks/new/$',
        TaskCreateView.as_view(),
        name='new'),
    url(r'^dreams/(?P<dream_slug>[-_\w]+)/plans/(?P<plan_slug>[-_\w]+)/tasks/(?P<pk>\d+)/$',
        TaskEditView.as_view(),
        name='edit'),
    url(r'^tasks/(?P<pk>\d+)/$',
        TaskEditView.as_view(),
        name='edit'),
)

idea_patterns = patterns('',
    # noqa
    url(r'^ideas/new/$',
        IdeaCreateView.as_view(),
        name='new'),
    url(r'^dreams/(?P<dream_slug>[-_\w]+)/ideas/$',
        IdeaListView.as_view(),
        name='list_for_dream'),
    # url(r'^dreams/(?P<dream_slug>[-_\w]+)/ideas/new/$',
    #     IdeaCreateView.as_view(),
    #     name='new_for_dream'),
    url(r'^dreams/(?P<dream_slug>[-_\w]+)/plans/(?P<plan_slug>[-_\w]+)/ideas/$',
        IdeaListView.as_view(),
        name='list_for_plan'),
    # url(r'^dreams/(?P<dream_slug>[-_\w]+)/plans/(?P<plan_slug>[-_\w]+)/ideas/new/$',
    #     IdeaCreateView.as_view(),
    #     name='new_for_plan'),
    url(r'^ideas/(?P<pk>\d+)/$',
        IdeaEditView.as_view(),
        name='edit'),
)

urlpatterns = patterns('',
    # noqa
    url(r'^', include(dream_patterns, namespace='dream')),
    url(r'^', include(plan_patterns, namespace='plan')),
    url(r'^', include(task_patterns, namespace='task')),
    url(r'^', include(idea_patterns, namespace='idea')),
    url(r'^admin/', include(admin.site.urls)),
)

dream/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.core.urlresolvers import reverse
from pytils.translit import translify


class SlugModelMixin(models.Model):
    slug = AutoSlugField(populate_from='slug_translit', db_index=True)

    @property
    def slug_translit(self):
        return translify(getattr(self, self.SLUG_SOURCE))

    class Meta:
        abstract = True


class CoreModel(models.Model):
    is_active = models.BooleanField('Active', default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class DreamManager(models.Manager):
    def actual_list(self):
        return self.get_queryset().filter(is_active=True)


class Dream(SlugModelMixin, CoreModel):
    SLUG_SOURCE = 'title'

    qq = models.TextField('QQ', blank=True, null=True)
    title = models.CharField('Title', max_length=255)
    description = models.TextField('Description', blank=True, null=True)
    completion_date = models.DateField('Completion date', blank=True, null=True)
    rating = models.IntegerField('Rating', blank=True, null=True)

    objects = DreamManager()

    class Meta:
        ordering = ('-rating',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('dream:edit', args=(self.slug,))

    def get_create_plan_url(self):
        return reverse('plan:new', args=(self.slug,))


class PlanManager(models.Manager):
    def actual_list(self):
        return self.get_queryset().filter(is_active=True)


class Plan(SlugModelMixin, CoreModel):
    SLUG_SOURCE = 'title'

    dream = models.ForeignKey(Dream, verbose_name='Dream', related_name='plans')
    qq = models.TextField('QQ', blank=True, null=True)
    title = models.CharField('Title', max_length=255)
    description = models.TextField('Description', blank=True, null=True)
    rating = models.IntegerField('Rating', blank=True, null=True)

    objects = PlanManager()

    class Meta:
        ordering = ('-rating',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('plan:edit', args=(self.dream.slug, self.slug,))

    def get_create_task_url(self):
        return reverse('task:new')


class TaskManager(models.Manager):
    def actual_list(self):
        return self.get_queryset().filter(is_active=True)

    def purchase_list(self):
        return self.actual_list().filter(is_purchase=True)

    def not_purchase_list(self):
        return self.actual_list().filter(is_purchase=False)

    def to_do_list(self):
        return self.not_purchase_list().filter(is_done=False)

    def with_plan_list(self):
        return self.to_do_list().filter(plan__isnull=False)

    def parents_with_plan_list(self):
        return self.with_plan_list().filter(parent_task__isnull=True)

    def without_plan_list(self):
        return self.to_do_list().filter(plan__isnull=True)

    def parents_without_plan_list(self):
        return self.without_plan_list().filter(parent_task__isnull=True)

    def parents_list(self):
        return self.actual_list().filter(parent_task__isnull=True)


class Task(CoreModel):
    plan = models.ForeignKey(Plan, verbose_name='Plan', related_name='tasks', blank=True, null=True)
    parent_task = models.ForeignKey(
        'self',
        limit_choices_to={
            'parent_task': None,
            # 'plan__isnull': False,
            'is_done': False,
            'is_purchase': False},
        verbose_name='Parent_task',
        related_name='child_tasks',
        blank=True, null=True)
    qq = models.TextField('QQ', blank=True, null=True)
    title = models.CharField('Title', max_length=255)
    description = models.TextField('Description', blank=True, null=True)
    start_date = models.DateField('Start date', blank=True, null=True)
    end_date = models.DateField('End date', blank=True, null=True)
    is_done = models.BooleanField('Done', default=False)
    is_purchase = models.BooleanField('Is Purchase', default=False)

    objects = TaskManager()

    class Meta:
        ordering = ('start_date', 'plan__dream', 'plan', 'id')

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        if self.plan:
            return reverse('task:edit', args=(self.plan.dream.slug, self.plan.slug, self.id,))
        else:
            return reverse('task:edit', args=(self.id,))


class IdeaManager(models.Manager):
    def actual_list(self):
        return self.get_queryset().filter(is_active=True)


class Idea(CoreModel):
    dream = models.ForeignKey(Dream, verbose_name='Dream', related_name='ideas', blank=True, null=True)
    plan = models.ForeignKey(Plan, verbose_name='Plan', related_name='ideas', blank=True, null=True)
    qq = models.TextField('QQ', blank=True, null=True)
    title = models.CharField('Title', max_length=255)
    description = models.TextField('Description', blank=True, null=True)

    objects = IdeaManager()

    class Meta:
        ordering = ('-updated',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('idea:edit', args=(self.id,))

dream/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from .models import Dream, Task


class DreamForm(forms.ModelForm):
    class Meta:
        model = Dream
        widgets = {
            'completion_date': SelectDateWidget,
        }


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        widgets = {
            'start_date': SelectDateWidget,
            'end_date': SelectDateWidget,
        }

dream/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView

from .utils import get_object_or_None

from .forms import DreamForm, TaskForm

from .models import Dream, Plan, Task, Idea


class DreamMixin(object):
    def get_context_data(self, **kwargs):
        context = super(DreamMixin, self).get_context_data(**kwargs)
        context['dream'] = get_object_or_None(Dream.objects.actual_list(), slug=self.kwargs.get('dream_slug'))
        return context


class PlanMixin(object):
    def get_context_data(self, **kwargs):
        context = super(PlanMixin, self).get_context_data(**kwargs)
        context['plan'] = get_object_or_None(Plan.objects.actual_list(), slug=self.kwargs.get('plan_slug'))
        return context


class DreamCreateView(CreateView):
    model = Dream
    form_class = DreamForm
    template_name_suffix = '_new_form'


class DreamEditView(UpdateView):
    model = Dream
    form_class = DreamForm
    template_name_suffix = '_edit_form'


class DreamListView(ListView):
    model = Dream
    queryset = Dream.objects.actual_list()


class PlanCreateView(DreamMixin, CreateView):
    model = Plan
    template_name_suffix = '_new_form'


class PlanEditView(DreamMixin, UpdateView):
    model = Plan
    template_name_suffix = '_edit_form'


class PlanListView(DreamMixin, ListView):
    model = Plan
    queryset = Plan.objects.actual_list()


class TaskCreateView(DreamMixin, PlanMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name_suffix = '_new_form'


class TaskEditView(DreamMixin, PlanMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name_suffix = '_edit_form'


class TaskToDoListView(DreamMixin, PlanMixin, ListView):
    model = Task
    queryset = Task.objects.to_do_list()

    def get_context_data(self, **kwargs):
        context = super(TaskToDoListView, self).get_context_data(**kwargs)
        context['parents_with_plan_list'] = Task.objects.parents_with_plan_list()
        context['parents_without_plan_list'] = Task.objects.parents_without_plan_list()
        return context


class TaskPurchasesListView(DreamMixin, PlanMixin, ListView):
    model = Task
    template_name = 'dream/task_purchase_list.html'
    queryset = Task.objects.purchase_list()


class IdeaCreateView(DreamMixin, PlanMixin, CreateView):
    model = Idea
    template_name_suffix = '_new_form'


class IdeaEditView(DreamMixin, PlanMixin, UpdateView):
    model = Idea
    template_name_suffix = '_edit_form'

    def get_context_data(self, **kwargs):
        context = super(IdeaEditView, self).get_context_data(**kwargs)
        context['dream'] = self.object.dream
        context['plan'] = self.object.plan
        return context


class IdeaListView(DreamMixin, PlanMixin, ListView):
    model = Idea
    queryset = Idea.objects.actual_list()

templates/dream/dream_edit_form.html
{% extends "base.html" %}
{% block content %}

<div>
  <form method="post" action="{{ dream.get_absolute_url }}">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
</div>

<div>
  <h2>Plans:</h2>
  <a href="{{ dream.get_create_plan_url }}"><button >Create Plan</button></a>
  <ul>
    {% for plan in dream.plans.actual_list %}
      <li>
        <h3><a href="{{ plan.get_absolute_url }}">{{ plan.title }}</a> tasks:</h3>
        <ul>
          {% for task in plan.tasks.parents_list %}
            <li>
              {% if task.is_done %}
                <input type="checkbox" disabled="disabled" checked>
              {% else %}
                <input type="checkbox" disabled="disabled">
              {% endif %}
              <a href="{{ task.get_absolute_url }}">{{ task.title }}</a>
              {% if task.child_tasks.actual_list.exists %}
                <ul>
                  {% for child_task in task.child_tasks.actual_list %}
                    <li>
                      {% if child_task.is_done %}
                        <input type="checkbox" disabled="disabled" checked>
                      {% else %}
                        <input type="checkbox" disabled="disabled">
                      {% endif %}
                      <a href="{{ child_task.get_absolute_url }}">{{ child_task.title }}</a>
                    </li>
                  {% endfor %}
                </ul>
              {% endif %}
            </li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>
</div>

<div>
  <h2>Ideas:</h2>
  <a href="{% url "idea:new" %}"><button >Create Idea</button></a>
  <ul>
    {% for idea in dream.ideas.actual_list %}
      <li>
        <a href="{{ idea.get_absolute_url }}">{{ idea.title }}</a>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock content %}

templates/dream/dream_list.html
{% extends "base.html" %}
{% block content %}
<div>
  <h1>Dreams:</h1>
  <a href="{% url "dream:new" %}"><button >Create Dream</button></a>
  <ul>
    {% for dream in dream_list %}
      <li>
        <h3>
          <a href="{{ dream.get_absolute_url }}">{{ dream.title }}</a>
          {% if dream.completion_date %}
            ({{ dream.completion_date|timeuntil }} remained)
          {% endif %}
        </h3>
      </li>
    {% endfor %}
  </ul>
</div>

<div>
  <h2><a href="{% url "task:to_do_list" %}">Tasks</a></h2>
</div>

<div>
  <h2><a href="{% url "task:purchase_list" %}">Purchases</a></h2>
</div>

<div>
  <textarea rows="15" cols="80"></textarea>
</div>
{% endblock content %}

templates/dream/dream_new_form.html
{% extends "base.html" %}
{% block content %}
<h1>New Dream</h1>
<form method="post" action="{% url 'dream:new' %}">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create" />
</form>
{% endblock content %}

templates/dream/idea_edit_form.html
{% extends "base.html" %}
{% block content %}

<form method="post" action="{{ form.instance.get_absolute_url }}">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/dream/idea_new_form.html
{% extends "base.html" %}
{% block content %}
<h1>New Idea</h1>
<form method="post" action="{% url "idea:new" %}">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create" />
</form>
{% endblock content %}

templates/dream/plan_edit_form.html
{% extends "base.html" %}
{% block content %}

<div>
  <form method="post" action="{{ plan.get_absolute_url }}">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
</div>

<div>
  <h2>Tasks:</h2>
  <a href="{{ plan.get_create_task_url }}"><button >Create Task</button></a>
  <ul>
    {% for task in plan.tasks.parents_list %}
      <li>
        {% if task.is_done %}
          <input type="checkbox" disabled="disabled" checked>
        {% else %}
          <input type="checkbox" disabled="disabled">
        {% endif %}
        <a href="{{ task.get_absolute_url }}">{{ task.title }}</a>
        {% if task.child_tasks.actual_list.exists %}
          <ul>
            {% for child_task in task.child_tasks.actual_list %}
              <li>
                {% if child_task.is_done %}
                  <input type="checkbox" disabled="disabled" checked>
                {% else %}
                  <input type="checkbox" disabled="disabled">
                {% endif %}
                <a href="{{ child_task.get_absolute_url }}">{{ child_task.title }}</a>
              </li>
            {% endfor %}
          </ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>

<div>
  <h2>Ideas:</h2>
  <a href="{% url "idea:new" %}"><button >Create Idea</button></a>
  <ul>
    {% for idea in plan.ideas.actual_list %}
      <li>
        <a href="{{ idea.get_absolute_url }}">{{ idea.title }}</a>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock content %}

templates/dream/plan_list.html
{% extends "base.html" %}
{% block content %}
{% for plan in plan_list %}
  {{ plan.title }}
{% endfor %}
{% endblock content %}

templates/dream/plan_new_form.html
{% extends "base.html" %}
{% block content %}
<h1>New Plan</h1>
<form method="post" action="{{ dream.get_create_plan_url }}">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create" />
</form>
{% endblock content %}

templates/dream/task_edit_form.html
{% extends "base.html" %}
{% block content %}

<form method="post" action="{{ task.get_absolute_url }}">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/dream/task_list.html
{% extends "base.html" %}
{% block content %}
<a href="{% url "task:new" %}"><button >Create Task</button></a>
<h2>Quick Tasks:</h2>
<div>
  <ul>
    {% for task in parents_without_plan_list %}
      <li>
        <a href="{{ task.get_absolute_url }}">{{ task.title }}</a>
        {% if task.child_tasks.to_do_list.exists %}
          <ul>
            {% for child_task in task.child_tasks.actual_list %}
              <li>
                <a href="{{ child_task.get_absolute_url }}">{{ child_task.title }}</a>
              </li>
            {% endfor %}
          </ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>

<h2>Tasks for plans:</h2>
<div>
  <ul>
    {% for task in parents_with_plan_list %}
        {% ifchanged task.start_date %}
          <li>
            <h3>{{ task.start_date|default:"Undated:" }}</h2>
          </li>
        {% endifchanged %}
      <li>
        <a href="{{ task.plan.dream.get_absolute_url }}">{{ task.plan.dream.title }}</a> / <a href="{{ task.plan.get_absolute_url }}">{{ task.plan.title }}</a> / <a href="{{ task.get_absolute_url }}">{{ task.title }}</a>
        {% if task.child_tasks.to_do_list.exists %}
          <ul>
            {% for child_task in task.child_tasks.to_do_list %}
              <li>
                <a href="{{ child_task.get_absolute_url }}">{{ child_task.title }}</a>
              </li>
            {% endfor %}
          </ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock content %}

templates/dream/task_new_form.html
{% extends "base.html" %}
{% block content %}
<h1>New Task</h1>
<form method="post" action="{{ plan.get_create_task_url }}">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create" />
</form>
{% endblock content %}

templates/dream/task_purchase_list.html
{% extends "base.html" %}
{% block content %}
<h1>Purchases</h1>
<a href="{% url "task:new" %}"><button >Create Purchase</button></a>
<div>
  <ul>
    {% for task in task_list %}
      <li>
        <a href="{{ task.get_absolute_url }}">{{ task.title }}</a>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock content %}